apiVersion: apps/v1
kind: Deployment
metadata:
  name: naysayer
  labels:
    app: naysayer
    component: webhook
spec:
  replicas: 2
  selector:
    matchLabels:
      app: naysayer
  template:
    metadata:
      labels:
        app: naysayer
        component: webhook
    spec:
      containers:
      - name: naysayer
        image: quay.io/ddis/naysayer:latest
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: GITLAB_BASE_URL
          value: "https://gitlab.com"
        - name: GITLAB_TOKEN
          valueFrom:
            secretKeyRef:
              name: naysayer-secrets
              key: gitlab-token
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Secret
metadata:
  name: naysayer-secrets
type: Opaque
data:
  # Add your base64-encoded GitLab token here
  # echo -n "your-gitlab-token" | base64
  gitlab-token: ""