apiVersion: apps/v1
kind: Deployment
metadata:
  name: naysayer
  namespace: ddis-asteroid--naysayer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: naysayer
  template:
    metadata:
      labels:
        app: naysayer
    spec:
      containers:
        - name: naysayer
          image: quay.io/ddis/naysayer:latest
          ports:
            - containerPort: 3000
              protocol: TCP
          env:
            - name: PORT
              value: '3000'
            - name: GITLAB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: naysayer-secrets
                  key: GITLAB_TOKEN
            - name: GITLAB_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: naysayer-secrets
                  key: GITLAB_BASE_URL
            - name: WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: naysayer-secrets
                  key: WEBHOOK_SECRET
            - name: WEBHOOK_VERIFY
              value: "true"
            - name: LOG_LEVEL
              value: "info"
            - name: ENVIRONMENT
              value: "production"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
      serviceAccountName: naysayer-deployment
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%