apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: naysayer
  namespace: ddis-asteroid--naysayer
spec:
  host: naysayer-webhook.your-domain.com  # Update with your actual domain
  to:
    kind: Service
    name: naysayer
    weight: 100
  port:
    targetPort: https
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
