# Rule configuration for naysayer
# All rules must approve for auto-approval (unanimous strategy)

rules:
  - name: "warehouse_rule"
    enabled: true
    description: "Approves warehouse size decreases, rejects increases"
    conditions:
      - field: "project_id"
        operator: "exists"
        value: true
    config:
      # No additional config needed for warehouse rule
      
  # - name: "security_rule"
  #   enabled: true
  #   description: "Blocks changes to sensitive files and configurations"
  #   conditions:
  #     - field: "project_id"
  #       operator: "exists" 
  #       value: true
  #   config:
  #     # Additional sensitive patterns can be added here
  #     additional_patterns:
  #       - "(?i)\\.secret$"
  #       - "(?i)backup\\.sql$"
  #     additional_files:
  #       - ".github/workflows/deploy.yml"
  #       - "scripts/deploy.sh"

# Example of how to add project-specific rules
# - name: "project_specific_rule"
#   enabled: true
#   description: "Custom rules for specific projects"
#   conditions:
#     - field: "project_id"
#       operator: "in"
#       value: [123, 456, 789]
#   config:
#     max_file_changes: 10
#     required_labels: ["reviewed", "tested"]

# Example of environment-specific rules  
# - name: "production_rule"
#   enabled: true
#   description: "Extra strict rules for production deployments"
#   conditions:
#     - field: "environment"
#       operator: "eq"
#       value: "production"
#   config:
#     require_manual_approval: true