kind: Service
apiVersion: v1
metadata:
  name: naysayer
  namespace: ddis-asteroid--naysayer
spec:
  ports:
  - name: https
    protocol: TCP
    port: 3000
    targetPort: 3000
  selector:
    app: naysayer