---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: naysayer-deployment
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: naysayer
  name: naysayer-deployment
  namespace: ddis-asteroid--naysayer 