---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: naysayer-hpa
  labels:
    app: naysayer
    component: webhook
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: naysayer
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30
      - type: Pods
        value: 2
        periodSeconds: 30
      selectPolicy: Max
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: naysayer-pdb
  labels:
    app: naysayer
    component: webhook
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: naysayer
      component: webhook
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: naysayer-network-policy
  labels:
    app: naysayer
    component: webhook
spec:
  podSelector:
    matchLabels:
      app: naysayer
      component: webhook
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-system  # Allow from ingress controller
    - podSelector:
        matchLabels:
          app: monitoring  # Allow from monitoring systems
    ports:
    - protocol: TCP
      port: 3000
  egress:
  - to: []  # Allow all outbound (GitLab API calls)
    ports:
    - protocol: TCP
      port: 443  # HTTPS
    - protocol: TCP
      port: 80   # HTTP
  - to: []  # DNS resolution
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
---
apiVersion: v1
kind: LimitRange
metadata:
  name: naysayer-limits
  labels:
    app: naysayer
    component: webhook
spec:
  limits:
  - default:
      memory: "256Mi"
      cpu: "200m"
      ephemeral-storage: "500Mi"
    defaultRequest:
      memory: "128Mi"
      cpu: "100m"
      ephemeral-storage: "100Mi"
    type: Container
  - max:
      memory: "512Mi"
      cpu: "500m"
      ephemeral-storage: "1Gi"
    min:
      memory: "64Mi"
      cpu: "50m"
      ephemeral-storage: "50Mi"
    type: Container
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: naysayer-quota
  labels:
    app: naysayer
    component: webhook
spec:
  hard:
    requests.cpu: "1"
    requests.memory: "1Gi"
    requests.ephemeral-storage: "2Gi"
    limits.cpu: "2"
    limits.memory: "2Gi"
    limits.ephemeral-storage: "4Gi"
    pods: "15"
    services: "5"
    secrets: "5"
    configmaps: "5"